---

version: '3.8'
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: reserve
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
    - db-data:/var/lib/mysql
  php:
    build: ./php
    depends_on:
    - db
    ports:
    - 8569:8000
    volumes:
    - ./work:/work

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: testuser
      PMA_PASSWORD: testpass
    ports:
      - "8089:80"

volumes:
  db-data: